sign-commit	= true
sign-tag = true
publish = false
pre-release-commit-message = "{{crate_name}} version {{version}}"
post-release-commit-message = "Working on {{crate_name}} version {{next_version}}"
dependent-version = "upgrade"
